resources:
- name: fantastic-barnacle
  type: git
  source:
    branch: master
    uri: https://github.com/acvwilson/fantastic-barnacle.git

jobs:
- name: performance
  public: true
  plan:
  - get: fantastic-barnacle
  - task: jmeter
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: justb4/jmeter}
      run:
        path: sh
        args:
        - -exc
        - |
            jmeter -n -t hello-world-performance.jmx > output
            cat output
            cat hello-world-performance.csv
            if grep "(0.00%)$" output
            then
              echo Success
              exit 0
            else
              echo Failure
              exit 1
            fi
        dir: fantastic-barnacle
      inputs:
      - name: fantastic-barnacle